module.exports = {
  WALLET_CREATED_BADGE_TYPE: 'wallet-created',
  WALLET_IMPORTED_BADGE_TYPE: 'wallet-imported',
  FIRST_CONNECTION_ESTABLISHED_BADGE_TYPE: 'first-connection-established',
  FIRST_TRANSACTION_MADE_TYPE: 'first-transaction-made',
  FIRST_TRANSACTION_RECEIVED_TYPE: 'first-transaction-received',
  EMAIL_VERIFIED_TYPE: 'email-verified',
  PHONE_VERIFIED_TYPE: 'phone-verified',
  REFERRAL_REWARD_RECEIVED_TYPE: 'referral-reward-received',
  FIRST_REFERRAL_SENT_TYPE: 'first-referral-sent',
  FIVE_REFERRALS_SENT_TYPE: 'five-referrals-sent',
  TEN_REFERRALS_SENT_TYPE: 'ten-referrals-sent',
  TWENTYFIVE_REFERRALS_SENT_TYPE: 'twentyfive-referrals-sent',
  HUNDRED_REFERRALS_SENT_TYPE: 'hundred-referrals-sent',
  FIRST_AAVE_DEPOSIT: 'first-aave-deposit',
};
